### ISSUE TITLE
Entry for newly added URL doesn't appear the first time Boards Manager is opened

### ISSUE THREAD

**Issue by per1234** [SpenceKonde/ReleaseScripts#5]
See https://github.com/arduino/Arduino/issues/3795 for an explanation of the issue. Can you confirm this issue? Arduino IDE 1.6.6 was released today with this issue(doesn't happen in 1.6.5) so if this is real(it happens consistently for me) I think a note should be added to the Boards Manager installation instructions for both cores, otherwise users are going to think the Boards Manager URL they added didn't work when the entry doesn't show up.

**Comment by SpenceKonde** [comment]
I'll test tonight... goddamnit...

**Comment by SpenceKonde** [comment]
Confirmed. I've updated the readme's appropriately. Is there anywhere else I should update it?

**Comment by per1234** [comment]
If you would add a comment to the issue confirming that it also happens for you it might help get priority on fixing it. I hope they will put out a 1.6.6r2 soon.
